spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.221.129:3306/shell?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /sell
